Feat#858 signup/prev next btn
Track1-client/client pull request #859
Opened 2023-12-18 11:15 UTC by seojisoosoo

### ✅ 구현 명세
회원가입의 prev, next 버튼을 구현했어요. 

### 📝 이렇게 구현해봣어요
step, setStep을 prop으로 내려주었어요.

### 🙌🏻 같이 고민했으면 하는 부분
데탑 버전에서는 버튼 disabled 여부를 isSuccess라는 이름의 전역변수로 사용했는데, 사실 disabled 여부는 다른 곳이 아니라 오직 회원가입 input(SingupMain에 해당하는 부분)에서만 결정되기 때문에, 리코일로 하는 게 맞을지 좀 고민이 되는 것 같아요.. context로 하기엔 부수적인 코드들이 많아질 것 같고 그냥 prop으로 내려줄까.. 생각중입니다. 결국 두 방법다 SingupMain과 StepButton 컴포넌트를 형제관계로 가지고 있던 데탑과 달리, StepButton을 SignupMain에 종속되게 하는 방법일 듯 하네용...

2023-12-20 06:39 UTC, NaveOWO requested changes

2023-12-20 06:39 UTC, NaveOWO commented on apps/mobile/src/components/signUp/SingupStep/StepButtons.tsx
> +  const [roleType, setRoleType] = useRecoilState<string | UserType>(role);
UserType에 null타입을 추가하거나  "Undefined"를 추가해서 타입을 좁히는게 좋을 것 같아요!

2023-12-20 06:39 UTC, NaveOWO commented on apps/mobile/src/components/signUp/SingupStep/StepButtons.tsx
> +    <div>
div 필요한가요?

2023-12-24 17:50 UTC, seojisoosoo commented on apps/mobile/src/components/signUp/SingupStep/StepButtons.tsx
> +  const [roleType, setRoleType] = useRecoilState<string | UserType>(role);
네!! 감사합니당

2023-12-24 17:51 UTC, seojisoosoo commented on apps/mobile/src/components/signUp/SingupStep/StepButtons.tsx
> +    <div>
아니유.. 이거 뷰들이 화면에 안 뜨는 이슈때문에 태그 넣어본 것인데, 이 문제때문은 아니어서 삭제하겠습니당

2023-12-29 17:21 UTC, merged